### PR TITLE
Make the sidekiq text into a link

### PR DESCRIPTION
**Pull request by tarebyte**
Hi There!

I just wanted a way to get to the sidekiq web view without having to make an extra button.

Very much open to feedback.

Thanks :sparkles:

### CODE REVIEW

**Comment by Soliah** [comment]
Looks good. Could you favour `"` over `'`.

**Comment by tarebyte** [comment]
@Soliah I had a thought, see what you think about this method. This way if the user defines the `sidekiq_web_path` then the peek view will just pick up on it.

**Comment by Soliah** [comment]
Ah yea thats good. Just change the single quotes to double quotes and I'll merge in.

**Comment by tarebyte** [comment]
@Soliah should be good to go, thanks!

**Comment by Soliah** [comment]
Thanks :heart:. Really should send a PR to https://github.com/peek/peek adding this to the readme.

**Pull request merged**
